# Generated by Django 3.1.1 on 2024-05-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('study_streem', models.CharField(blank=True, max_length=20, null=True)),
                ('collage', models.CharField(blank=True, max_length=20, null=True)),
                ('DOB', models.DateField(blank=True, default=False, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_started_date', models.DateTimeField()),
                ('last_follow_up', models.DateField(blank=True, null=True)),
                ('number_follow_up', models.PositiveBigIntegerField(default=0)),
                ('follow_up_status', models.CharField(choices=[('RNA', 'RNA'), ('Not Taken', 'Not Taken'), ('Not intrested', 'Not intrested'), ('Line Busy', 'Line Busy'), ('Intrested', 'Intrested'), ('Sligtly Intrested', 'Sligtly Intrested'), ('Call Back', 'Call Back')], default='Not Called', max_length=20)),
                ('last_status', models.TextField(max_length=1000)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('lead_status', models.CharField(choices=[('1', 'Warm Lead'), ('2', 'Hot Lead'), ('3', 'Pending'), ('4', 'Converted'), ('5', 'Rejected')], default='Normal', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('lead_follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCallStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_follow_up', models.DateTimeField(auto_now_add=True)),
                ('follow_up_status', models.CharField(choices=[('RNA', 'RNA'), ('Not Taken', 'Not Taken'), ('Not intrested', 'Not intrested'), ('Line Busy', 'Line Busy'), ('Intrested', 'Intrested'), ('Sligtly Intrested', 'Sligtly Intrested'), ('Call Back', 'Call Back')], default='Not Called', max_length=20)),
                ('follow_up_comments', models.TextField(max_length=1055)),
                ('next_follow_up', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.studentcontact')),
                ('follow_up_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
