# Generated by Django 3.1.1 on 2024-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='last_status',
            field=models.TextField(blank=True, default='Fresh Data', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('1', 'Warm Lead'), ('2', 'Hot Lead'), ('3', 'Pending'), ('4', 'Converted'), ('5', 'Rejected')], default='Normal', max_length=255, null=True),
        ),
    ]
