# Generated by Django 3.1.1 on 2024-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_auto_20240504_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='follow_up_status',
            field=models.CharField(choices=[('Not Called', 'Not Called'), ('RNA', 'RNA'), ('Not Taken', 'Not Taken'), ('Not intrested', 'Not intrested'), ('Line Busy', 'Line Busy'), ('Intrested', 'Intrested'), ('Sligtly Intrested', 'Sligtly Intrested'), ('Call Back', 'Call Back')], default='Not Called', max_length=20),
        ),
    ]
