# Generated by Django 3.1.1 on 2024-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0005_auto_20240504_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
