# Generated by Django 5.0.6 on 2025-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0006_auto_20240504_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcallstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='follow_up_status',
            field=models.CharField(choices=[('Not Called', 'Not Called'), ('RNR', 'RNR'), ('Not Taken', 'Not Taken'), ('Not intrested', 'Not intrested'), ('Line Busy', 'Line Busy'), ('Intrested', 'Intrested'), ('Sligtly Intrested', 'Sligtly Intrested'), ('Call Back', 'Call Back')], default='Not Called', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('Warm Lead', 'Warm Lead'), ('Hot Lead', 'Hot Lead'), ('Pending', 'Pending'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Normal', max_length=255, null=True),
        ),
    ]
