# Generated by Django 5.0.6 on 2025-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240422_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
