# Generated by Django 5.0.6 on 2025-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_companyprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='letter_head_bottom',
            field=models.FileField(blank=True, null=True, upload_to='letter_head_bottom'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='letter_head_top',
            field=models.FileField(blank=True, null=True, upload_to='letter_head_top'),
        ),
    ]
